<?php
// $Autho: wishcraft $
//  ------------------------------------------------------------------------ //
//                XOOPS - PHP Content Management System                      //
//                    Copyright (c) 2009 XOOPS.org                           //
//                       <http://www.xoops.org/>                             //
//  ------------------------------------------------------------------------ //
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  You may not change or alter any portion of this comment or credits       //
//  of supporting developers from this source code or any supporting         //
//  source code which is considered copyrighted (c) material of the          //
//  original comment or credit authors.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//                                                                           //
//  You should have received a copy of the GNU General Public License        //
//  along with this program; if not, write to the Free Software              //
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA //
//  ------------------------------------------------------------------------ //
//  --  Author: Simon Roberts (simon@chronolabs.org.au)                   -- //
//  ------------------------------------------------------------------------ //

$modversion['name'] = _XV_XTRANSAM_NAME;
$modversion['version'] = 1.12;
$modversion['description'] = _XV_XTRANSAM_DESC;
$modversion['author'] = "Wishcraft";
$modversion['credits'] = "The XOOPS Project";
$modversion['help'] = "xtransam.html";
$modversion['license'] = "GPL see LICENSE";
$modversion['official'] = 1;
$modversion['status']  = "Stable";
$modversion['image'] = "images/xtransam_slogo.png";
$modversion['dirname'] = "xtransam";

$modversion['author_realname'] = "Simon Antony Roberts";
$modversion['author_website_url'] = "http://www.chronolabs.org.au";
$modversion['author_website_name'] = "Chronolabs Australia";
$modversion['author_email'] = "simon@chronolabs.coop";
$modversion['demo_site_url'] = "Chronolabs Australia";
$modversion['demo_site_name'] = "";
$modversion['support_site_url'] = "http://www.chronolabs.org.au/forums/viewforum.php?forum=30";
$modversion['support_site_name'] = "Chronolabs";
$modversion['submit_bug'] = "http://www.chronolabs.org.au/forums/viewforum.php?forum=30";
$modversion['submit_feature'] = "http://www.chronolabs.org.au/forums/viewforum.php?forum=30";
$modversion['usenet_group'] = "sci.chronolabs";
$modversion['maillist_announcements'] = "";
$modversion['maillist_bugs'] = "";
$modversion['maillist_features'] = "";

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";

$modversion['onUpdate'] = "include/update.php";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";
// $modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";
// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "xtransam_files";
$modversion['tables'][1] = "xtransam_iobase";
$modversion['tables'][2] = "xtransam_languages";
$modversion['tables'][3] = "xtransam_translator";

// Menu
$modversion['hasMain'] = 0;

$modversion['config'][0]['name'] = 'store_method';
$modversion['config'][0]['title'] = '_XTL_STORE_METHOD';
$modversion['config'][0]['description'] = '_XTL_STORE_METHODDESC';
$modversion['config'][0]['formtype'] = 'select';
$modversion['config'][0]['valuetype'] = 'text';
$modversion['config'][0]['default'] = 'urlcode';
$modversion['config'][0]['options'] = array(	'URL Code Store Method' => 'urlcode',
												'UU Code Store Method' => 'uucode',
												'Base64 Code Store Method' => 'base64',
												'Hexadecimal Store Method' => 'hex',
												'Open Store Method' => 'open');

$i++;
$modversion['config'][1]['name'] = 'google_api_key';
$modversion['config'][1]['title'] = "_XTL_GOOGLE_APIKEY";
$modversion['config'][1]['description'] = "_XTL_GOOGLE_APIKEYDESC";
$modversion['config'][1]['formtype'] = 'text';
$modversion['config'][1]['valuetype'] = 'text';
$modversion['config'][1]['default'] = 'AIzaSyBYGuH0SpcsxL09148ClRErbsEEneFKC9g';
?>
